version: '3.7'
services:
  flask-app:
    build: .
    container_name: bff-flask-daruix
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres_admin:postgres6348@db:5500/sgo-daruix-db  # Usando a porta 5500
    depends_on:
      - db
    volumes:
      - .:/bff-flask-daruix  # Para sincronizar o código local com o container
    restart: unless-stopped

  db:
    image: postgres:14
    container_name: sgo-daruix-db
    environment:
      POSTGRES_USER: postgres_admin
      POSTGRES_PASSWORD: postgres6348
      POSTGRES_DB: sgo-daruix-db
    volumes:
      - pgdata:/var/lib/postgresql/data  # Persistência de dados
    ports:
      - "5500:5500"  # Porta personalizada para o PostgreSQL (5500)

volumes:
  pgdata:  # Persistência do banco de dados
