name: Deploy Flask on VPS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/github-actions
          chmod 600 ~/.ssh/github-actions
          ssh-keyscan 177.153.60.157 >> ~/.ssh/known_hosts

      - name: Deploy via SSH
        run: |
          ssh -i ~/.ssh/github-actions ricardo@177.153.60.157 << 'EOF'
            cd /opt/flask-deploy
            git pull origin main
            docker-compose down
            docker-compose up -d --build
          EOF
