name: Deploy Flask on VPS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Instalar SSH Client
        run: sudo apt-get install openssh-client -y

      - name: Adicionar chave SSH privada
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 177.153.60.157 >> ~/.ssh/known_hosts

      - name: Fazer deploy via SSH na VPS
        run: |
          ssh -i ~/.ssh/id_rsa ricardo@177.153.60.157 << 'EOF'
            cd /opt/flask-deploy
            git pull origin main
            docker-compose down
            docker-compose up -d --build
          EOF
