name: Deploy Flask on VPS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Chamar endpoint de deploy no servidor
        run: |
          curl -X POST http://177.153.60.157:8000/update_deploy \
          -H "X-DEPLOY-TOKEN: ${{ secrets.DEPLOY_SECRET }}"
